### ISSUE TITLE
Ícone do aplicativo

### ISSUE THREAD

**Issue by rafaelcoutinho** [rafaelcoutinho/northapp#1]
Criar um ícone 192x192 px para o aplicativo.

**Comment by wilsonhirai** [comment]
![icone1](https://cloud.githubusercontent.com/assets/16938325/12652701/2fe57360-c5d3-11e5-9fd4-ab7d2512b15a.png)

**Comment by wilsonhirai** [comment]
Rafael, não gostei muito o ícone. Não achei uma combinação de cores que ficasse legal. Mas isso podemos modificar depois, né? Segue um modelo inicial, o splash também não está do jeito que quero, mas estou enviando para não te atrasar.
Estamos com muitos eventos essa semana, temos 4 eventos seguidos.
Semana que vem estou mais tranquilo e faço uma coisa melhor.
Obrigado!

**Comment by rafaelcoutinho** [comment]
Fique tranquilo, não precisa enviar tudo de uma vez. 

E sim! sempre podemos trocar.
