### ISSUE TITLE
inscricao no celular nao esta abrindo senha de email existente

### ISSUE THREAD

**Issue by rafaelcoutinho** [rafaelcoutinho/northapp#113]

**Comment by rafaelcoutinho** [comment]
@wilsonhirai Voce pode confirmar com a Fabiana como ela fez para isso acontecer?

Hoje na reuniao ela estava tentando colocar o email para inscrever e nao estava abrindo a secao de senha.

**Comment by wilsonhirai** [comment]
@rafaelcoutinho Ela entrou em Meu Perfil e tentou logar sem ser pelo facebook, aí digitou o email dela. Aí não apareceu o campo senha para ela digitar.
Já tinha acontecido isso comigo uma vez, mas aí fechei o aplicativo e abri de novo e funcionou. Com ela não funcionava nem assim...

**Comment by rafaelcoutinho** [comment]
entendi mas como faço pra reproduzir o problema? @wilsonhirai
