### ISSUE TITLE
Notificação pros ainda não inscritos

### ISSUE THREAD

**Issue by rafaelcoutinho** [rafaelcoutinho/northapp#140]
@wilsonhirai o que acha desta opção? Enviar uma notificacação pros que tem o app mas ainda não se inscreveram

**Comment by wilsonhirai** [comment]
Acho bem legal isso aí Rafael! Se der pra fazer vai ser muito bom!

**Comment by rafaelcoutinho** [comment]
@wilsonhirai coloquei lá nas notificações. A gente pode testar na proxima etapa.

**Comment by wilsonhirai** [comment]
Excelente Rafael!
A gente sempre perde muito tempo separando e-mails e telefones de pessoas não inscritas.

Você consegue fazer um relatório com essas pessoas pra gente? Assim a gente consegue também abordar as pessoas que não tem aplicativo...

Se possível, tá? 

Obrigado!

**Comment by rafaelcoutinho** [comment]
sim, mas vou criar um ticket pra isso separado, quando der eu implemento
