### ISSUE TITLE
Splash Screen

### ISSUE THREAD

**Issue by rafaelcoutinho** [rafaelcoutinho/northapp#2]
Criar Tela Splash para o aplicativo, uma imagem de 2208x2208 px onde o centro será sempre visivel

**Comment by wilsonhirai** [comment]
![splash](https://cloud.githubusercontent.com/assets/16938325/12652849/f4099ffa-c5d3-11e5-83f3-4df2088cdc5a.png)

**Comment by rafaelcoutinho** [comment]
no aplicativo ficou muito legal!
