### ISSUE TITLE
Icone com resolução 70 dpi e 1024x1024

### ISSUE THREAD

**Issue by rafaelcoutinho** [rafaelcoutinho/northapp#22]
Para a apple precisamos de um ícone grande assim Você poderia gerá-lo?

**Comment by wilsonhirai** [comment]
Esse é o da App Store né? Se for já está ok!

**Comment by rafaelcoutinho** [comment]
sim! Beleza!

Rafael Coutinho
Software Engineer
Professional profile: www.linkedin.com/in/rafaelcoutinho
