### ISSUE TITLE
Editar dados do aplicativo playstore da Google

### ISSUE THREAD

**Issue by rafaelcoutinho** [rafaelcoutinho/northapp#25]
Precisamos que a parte de listagem no loja do google seja atualizada. Adicionando banners/icones e textos.
https://play.google.com/apps/publish/?dev_acc=08348768568102177597#MarketListingPlace:p=com.northbrasil.app

**Comment by wilsonhirai** [comment]
Rafael, acho que tá tudo certo. Preenchi os dados e coloquei as imagens na Play Store e App Store.
Se achar algo de errado aí, é só me avisar que eu mudo!
