### ISSUE TITLE
Opção Remover Equipe do Grid 

### ISSUE THREAD

**Issue by rafaelcoutinho** [rafaelcoutinho/northapp#41]

**Comment by rafaelcoutinho** [comment]
@wilsonhirai Na verdade não deveria remover a inscrição certo? Só remover a equipe do grid. Depois pode-se editar a inscricao separadamente.

**Comment by wilsonhirai** [comment]
Correto! seria melhor não remover a inscrição, pode ter um status de cancelado, por exemplo, com uma cor diferente. Assim a Fabi já sabe o que aconteceu com a equipe só de bater o olho.

**Comment by rafaelcoutinho** [comment]
Ok, por enquanto deixei um relatorio dizendo que aquela equipe tem inscricao paga, mas está fora do grid.
