### ISSUE TITLE
Se apertar Enter para salvar um competidor novo, os campos são zerados e não salva o competidor.

### ISSUE THREAD

**Issue by rafaelcoutinho** [rafaelcoutinho/northapp#49]

**Comment by rafaelcoutinho** [comment]
@wilsonhirai isto em inscrição OU no admin?

**Comment by wilsonhirai** [comment]
em inscrição

**Comment by rafaelcoutinho** [comment]
Ok consertei, agora ele não envia. Depois decidimos se ao dar enter ele deve ir para o campo telefone ou enviar o formulário (prefiro a 1a opção)
