### ISSUE TITLE
Um mesmo PC pode aparecer duas vezes na mesma prova

### ISSUE THREAD

**Issue by rafaelcoutinho** [rafaelcoutinho/northapp#66]
Tipo 2 tempos para o PC 8?

O contrário eu sei, um mesmo PC físico representa 2 PCs da prova certo?
@wilsonhirai

**Comment by wilsonhirai** [comment]
A equipe pode ter quantos tempos quiser, se ela plugar o chip 10 vezes, vai aparecer 10 tempos da equipe no PC, porém só vale o primeiro tempo, o programa de apuração descarta automaticamente os outros tempos. Já o PC físíco representar 2 PCs sim, pode ser que aconteça. É o caso do PC duplo, neste caso, para a apuração são 2 PCs diferentes, o Anselmo vê manualmente os quais são os tempos da segunda passagem pelo PC e move todos esses tempos para um PC diferente. Para a gente não interfere em nada, já que o tabelão de pontos já está com todas essas alterações.
