### ISSUE TITLE
Como calculo a pontuação geral

### ISSUE THREAD

**Issue by rafaelcoutinho** [rafaelcoutinho/northapp#67]
É baseado na posição do cara na prova certo?
@wilsonhirai

**Comment by wilsonhirai** [comment]
Sim baseado na colocação na prova, existe uma tabela de pontuação conforme anexo.
[PONTOS NA COPA.xlsx](https://github.com/rafaelcoutinho/northapp/files/206786/PONTOS.NA.COPA.xlsx)
