### ISSUE TITLE
Quanto vocês editam os resultados da prova

### ISSUE THREAD

**Issue by rafaelcoutinho** [rafaelcoutinho/northapp#68]
Há alguma correção manual no Tabelão depois das provas?

@wilsonhirai

**Comment by wilsonhirai** [comment]
Depois das provas é muito difícil haver alterações. Quando isso ocorre é porque houve um erro na apuração por parte nossa. Que eu me lembre isso foi feito apenas 2 vezes, que alterou a colocação de 2 equipes apenas.
