### ISSUE TITLE
Formato do Tabelão

### ISSUE THREAD

**Issue by rafaelcoutinho** [rafaelcoutinho/northapp#70]
Parece que o tabelão que você me mandou da etapa do casarão é diferente do danape. 
Como funciona essa exportação pro tabelão? podemos definir as colunas?

**Comment by wilsonhirai** [comment]
Na hora de exportar o tabelão, tem várias opções para colocar.
Vou ver aqui quais colunas podemos incluir ou excluir.
Preciso ver isso com o Anselmo, aí eu te retorno, ok?

**Comment by rafaelcoutinho** [comment]
Ok, vamos ter que ter uma seleção fixa pra importar no aplicativo. Escreve aqui quais são as opções e definimos se precisamos de mais.
