### ISSUE TITLE
Na planilha, alguns PCs cancelados aparecem com *0

### ISSUE THREAD

**Issue by rafaelcoutinho** [rafaelcoutinho/northapp#71]
O que significa?

**Comment by wilsonhirai** [comment]
É um código para visualização do resultado, toda vez que tiver um * na frente do resultado é porque houve algum problema, ou o PC foi cancelado ou a equipe perdeu o PC. Pra gente não importa, na verdade esses sinais devem sair né? inclusive o sinal de negativo

**Comment by rafaelcoutinho** [comment]
sim, já converti os *900 e os negativos eu estou somando. EStá quase lá.
Mas na coluna de PCs cancelados tem uns que aparecem 0 e outros que aparecem com *0..

entendi que não faz diferença.
