### ISSUE TITLE
ios select com probs

### ISSUE THREAD

**Issue by rafaelcoutinho** [rafaelcoutinho/northapp#74]

**Comment by rafaelcoutinho** [comment]
@wilsonhirai @FelipeFROliveira Vocês podem confirmar que está corrigido na versão 0.0.9 do test flight?
Aparentemente no iOS não tem como fechar ao clicar, tem que clicar no DONE que fica logo acima da lista.

**Comment by wilsonhirai** [comment]
@rafaelcoutinho acho que está ok! Mexi um pouco aqui nos menus e tudo mais e não deu nenhum erro. Acho que a opção de clicar em done já melhora bastante, antes dava uma impressão que não estava funcionando.
